import React, { useState, useEffect, useCallback, useRef } from 'react';
import {
  Measurement,
  ReportData,
  API_CONFIG,
  createEmptyMeasurement,
} from './constants';
import {
  autoGenerateDescription,
  extractHighestBiRads,
  generateRecommendation,
  sortMeasurementsByFrame,
} from './utils';
import SRReportTable from './SRReportTable';
import LoginModal from './LoginModal';
import './SRReport.css';

const DEFAULT_PHRASES: Record<string, string> = {
  benign: 'Benign-appearing lesion with circumscribed margins.',
  suspicious: 'Suspicious mass with irregular margins and posterior shadowing.',
  followup: 'Recommend short-interval follow-up in 6 months.',
  biopsy: 'Biopsy recommended for definitive diagnosis.',
};

const SRReport: React.FC = () => {
  const [reportData, setReportData] = useState<ReportData | null>(null);
  const [measurements, setMeasurements] = useState<Measurement[]>([]);
  const [description, setDescription] = useState('');
  const [statusMessage, setStatusMessage] = useState<{ text: string; type: 'success' | 'error' } | null>(null);
  const [showLoginModal, setShowLoginModal] = useState(false);
  const [sessionId, setSessionId] = useState('');
  const [accessToken, setAccessToken] = useState('');
  const [pendingAction, setPendingAction] = useState<'report' | 'pdf' | null>(null);
  const [phrases, setPhrases] = useState<Record<string, string>>(DEFAULT_PHRASES);
  const [selectedPhrase, setSelectedPhrase] = useState('');
  const [isSavingPdf, setIsSavingPdf] = useState(false);
  const textareaRef = useRef<HTMLTextAreaElement>(null);
  const statusTimeoutRef = useRef<ReturnType<typeof setTimeout>>();

  // Load SR data from localStorage
  useEffect(() => {
    try {
      const dataStr = localStorage.getItem('ohif_sr_report_data');
      if (!dataStr) {
        showStatus('No SR data found. Please open this page from USMPR Report button.', 'error');
        return;
      }

      const data: ReportData = JSON.parse(dataStr);
      const sorted = sortMeasurementsByFrame(data.measurements || []);

      setReportData(data);
      setMeasurements(sorted);

      if (sorted.length > 0) {
        showStatus(`Loaded ${sorted.length} measurement(s) successfully.`, 'success');
      } else {
        showStatus('No measurements found in SR data. You can add rows manually.', 'error');
      }
    } catch (error) {
      console.error('Failed to load SR data:', error);
      showStatus('Failed to load SR data: ' + (error as Error).message, 'error');
    }
  }, []);

  // Load premade phrases
  useEffect(() => {
    const stored = localStorage.getItem('ohif_premade_phrases');
    if (stored) {
      try {
        setPhrases(JSON.parse(stored));
      } catch (e) {
        console.error('Failed to parse stored phrases:', e);
      }
    } else {
      localStorage.setItem('ohif_premade_phrases', JSON.stringify(DEFAULT_PHRASES));
    }
  }, []);

  // Try to restore session from sessionStorage
  useEffect(() => {
    const storedSessionId = sessionStorage.getItem('session_id');
    const storedToken = sessionStorage.getItem('access_token');
    if (storedSessionId) setSessionId(storedSessionId);
    if (storedToken) setAccessToken(storedToken);
  }, []);

  const showStatus = useCallback((text: string, type: 'success' | 'error') => {
    setStatusMessage({ text, type });
    if (statusTimeoutRef.current) {
      clearTimeout(statusTimeoutRef.current);
    }
    statusTimeoutRef.current = setTimeout(() => setStatusMessage(null), 5000);
  }, []);

  const handleUpdateMeasurement = useCallback(
    (index: number, field: keyof Measurement, value: string | boolean) => {
      setMeasurements(prev => {
        const updated = [...prev];
        updated[index] = { ...updated[index], [field]: value };
        return updated;
      });
    },
    []
  );

  const handleAddRow = useCallback(() => {
    setMeasurements(prev => [...prev, createEmptyMeasurement()]);
  }, []);

  const handleDeleteSelected = useCallback(() => {
    const checkboxes = document.querySelectorAll<HTMLInputElement>('.row-select:checked');
    const indices = Array.from(checkboxes)
      .map(cb => parseInt(cb.dataset.index || '0'))
      .sort((a, b) => b - a);

    if (indices.length === 0) {
      alert('Please select rows to delete.');
      return;
    }

    if (confirm(`Delete ${indices.length} row(s)?`)) {
      setMeasurements(prev => {
        const updated = [...prev];
        indices.forEach(i => updated.splice(i, 1));
        return updated;
      });
    }
  }, []);

  const handleAutoGenerate = useCallback(() => {
    if (measurements.length === 0) {
      alert('No measurements to generate description from.');
      return;
    }
    setDescription(autoGenerateDescription(measurements));
  }, [measurements]);

  const handleInsertPhrase = useCallback(() => {
    if (!selectedPhrase) {
      alert('Please select a phrase first.');
      return;
    }

    const textarea = textareaRef.current;
    if (!textarea) return;

    const start = textarea.selectionStart;
    const end = textarea.selectionEnd;
    const text = textarea.value;

    const newText = text.substring(0, start) + selectedPhrase + text.substring(end);
    setDescription(newText);

    setTimeout(() => {
      textarea.focus();
      textarea.setSelectionRange(start + selectedPhrase.length, start + selectedPhrase.length);
    }, 0);
  }, [selectedPhrase]);

  const handleManagePhrases = useCallback(() => {
    const current = JSON.stringify(phrases, null, 2);
    const newPhrases = prompt(
      'Edit premade phrases (JSON format):\n\nFormat: {"key": "phrase text"}',
      current
    );
    if (newPhrases) {
      try {
        const parsed = JSON.parse(newPhrases);
        localStorage.setItem('ohif_premade_phrases', JSON.stringify(parsed));
        setPhrases(parsed);
        alert('Phrases updated successfully!');
      } catch (e) {
        alert('Invalid JSON format. Please check your syntax.');
      }
    }
  }, [phrases]);

  const handleLoginSuccess = useCallback(
    (newSessionId: string, newAccessToken: string) => {
      setSessionId(newSessionId);
      setAccessToken(newAccessToken);
      setShowLoginModal(false);

      if (pendingAction === 'report') {
        submitReport(newSessionId, newAccessToken);
      } else if (pendingAction === 'pdf') {
        submitPdf(newSessionId);
      }
      setPendingAction(null);
    },
    [pendingAction]
  );

  const handleSendReport = useCallback(() => {
    if (!description.trim()) {
      alert('Please enter a report description before submitting.');
      return;
    }

    if (sessionId && accessToken) {
      submitReport(sessionId, accessToken);
    } else {
      setPendingAction('report');
      setShowLoginModal(true);
    }
  }, [description, sessionId, accessToken]);

  const handleSavePdf = useCallback(() => {
    if (measurements.length === 0) {
      alert('No measurements to save. Please add measurements first.');
      return;
    }
    if (!description.trim()) {
      alert('Please enter a report description before saving PDF.');
      return;
    }

    if (sessionId) {
      submitPdf(sessionId);
    } else {
      setPendingAction('pdf');
      setShowLoginModal(true);
    }
  }, [measurements, description, sessionId]);

  const submitReport = async (sid: string, token: string) => {
    if (!reportData) return;

    try {
      const cleanMeasurements = measurements.map(m => ({
        uid: m.uid,
        toolName: (m as any).rawData?.toolName || (m as any).toolName || 'EllipticalROI',
        frameRange: m.frameRange,
        position: m.position,
        size: m.size,
        maxSurfVol: m.maxSurfVol,
        nature: m.nature,
        biRads: m.biRads,
        maligPercent: m.maligPercent,
        echo: m.echo,
        shape: m.shape,
        orientation: m.orientation,
        margin: m.margin,
      }));

      const payload = {
        studyInstanceUID: reportData.studyInstanceUID,
        seriesInstanceUID: reportData.seriesInstanceUID,
        patientID: reportData.patientID,
        patientName: reportData.patientName,
        measurements: cleanMeasurements,
        description,
        timestamp: new Date().toISOString(),
      };

      console.log('[SR Report] Request payload:', payload);

      const response = await fetch(API_CONFIG.reportEndpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          Authorization: `Bearer ${token}`,
          'X-Session-Id': sid,
        },
        body: JSON.stringify(payload),
      });

      console.log(`[SR Report] Response status: ${response.status} ${response.statusText}`);

      if (!response.ok) {
        let errorMessage = `Server responded with ${response.status}`;
        try {
          const errorText = await response.text();
          console.error('[SR Report] Error response body (raw):', errorText);
          try {
            const errorJson = JSON.parse(errorText);
            console.error('[SR Report] Parsed error JSON:', JSON.stringify(errorJson, null, 2));
            if (Array.isArray(errorJson)) {
              errorMessage = errorJson.map(e => `${e.loc?.join('.')}: ${e.msg}`).join('\n');
            } else if (errorJson.detail) {
              if (Array.isArray(errorJson.detail)) {
                errorMessage = errorJson.detail.map((e: any) => `${e.loc?.join('.')}: ${e.msg}`).join('\n');
              } else {
                errorMessage = typeof errorJson.detail === 'string' ? errorJson.detail : JSON.stringify(errorJson.detail);
              }
            } else {
              errorMessage = errorJson.message || JSON.stringify(errorJson);
            }
          } catch {
            errorMessage = errorText || errorMessage;
          }
        } catch {
          // Could not read response body
        }
        throw new Error(errorMessage);
      }

      const result = await response.json();
      console.log('[SR Report] Success:', result);
      showStatus('Report submitted successfully!', 'success');
      alert('Report submitted successfully!');
    } catch (error) {
      console.error('[SR Report] Error:', error);
      showStatus('Report submission failed: ' + (error as Error).message, 'error');
      alert('Failed to submit report:\n' + (error as Error).message);
    }
  };

  const submitPdf = async (sid: string) => {
    if (!reportData) return;

    setIsSavingPdf(true);

    try {
      const finalBirads = extractHighestBiRads(measurements);
      const recommendation = generateRecommendation(finalBirads);

      const lesions = measurements.map(m => ({
        position: m.position || '',
        size: m.size || '',
        nature: m.nature || 'Mass',
        biRads: m.biRads || '',
        echo: m.echo || '',
        shape: m.shape || '',
        orientation: m.orientation || '',
        margin: m.margin || '',
      }));

      const payload = {
        studyInstanceUID: reportData.studyInstanceUID,
        seriesInstanceUID: reportData.seriesInstanceUID,
        patientID: reportData.patientID,
        patientName: reportData.patientName,
        lesions,
        patientSex: reportData.patientSex || null,
        patientBirthDate: reportData.patientBirthDate || null,
        studyDate:
          reportData.studyDate || new Date().toISOString().split('T')[0].replace(/-/g, ''),
        accessionNumber: reportData.accessionNumber || null,
        reportDate: new Date().toISOString().split('T')[0].replace(/-/g, ''),
        reportTitle: 'BREAST ULTRASOUND REPORT',
        radiologist: reportData.radiologist || 'Dr. Unknown',
        description,
        finalBirads,
        breastComposition: reportData.breastComposition || null,
        ductDilatation: reportData.ductDilatation || 'None',
        recommendation,
      };

      console.log('[PDF Export] Request payload:', payload);

      const response = await fetch(API_CONFIG.pdfEndpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'X-Session-Id': sid,
        },
        body: JSON.stringify(payload),
      });

      console.log(`[PDF Export] Response status: ${response.status} ${response.statusText}`);

      if (!response.ok) {
        let errorMessage = `Server responded with ${response.status}`;
        try {
          const errorText = await response.text();
          try {
            const errorJson = JSON.parse(errorText);
            errorMessage = errorJson.message || errorJson.detail || errorMessage;
          } catch {
            errorMessage = errorText || errorMessage;
          }
        } catch {
          // Could not read response body
        }
        throw new Error(errorMessage);
      }

      const result = await response.json();
      console.log('[PDF Export] Success:', result);

      if (!result.success) {
        throw new Error(result.message || 'Unknown error from PDF server');
      }

      if (!result.data || !result.data.sopInstanceUID) {
        throw new Error('Server response missing required data.sopInstanceUID');
      }

      showStatus(
        result.message || `PDF DICOM created successfully (${lesions.length} lesion(s))`,
        'success'
      );
      alert(
        `PDF saved successfully!\n\nSOP Instance UID: ${result.data.sopInstanceUID}\nPACS Status: ${result.data.pacsStatus || 'OK'}`
      );
    } catch (error) {
      console.error('[PDF Export] Error:', error);
      showStatus('PDF save failed: ' + (error as Error).message, 'error');
      alert('Failed to save PDF:\n' + (error as Error).message);
    } finally {
      setIsSavingPdf(false);
    }
  };

  return (
    <div className="sr-container">
      <h1 className="sr-title">SR Report</h1>

      {/* Patient Info */}
      <div className="sr-patient-info">
        <div>
          <strong>Patient ID:</strong> <span>{reportData?.patientID || '-'}</span>
        </div>
        <div>
          <strong>Patient Name:</strong> <span>{reportData?.patientName || 'Loading...'}</span>
        </div>
        <div>
          <strong>Study Date:</strong> <span>{reportData?.studyDate || '-'}</span>
        </div>
      </div>

      {/* Status Message */}
      {statusMessage && (
        <div className={`sr-status sr-status-${statusMessage.type}`}>{statusMessage.text}</div>
      )}

      {/* Measurements Table */}
      <SRReportTable
        measurements={measurements}
        onUpdate={handleUpdateMeasurement}
        onAddRow={handleAddRow}
        onDeleteSelected={handleDeleteSelected}
      />

      {/* Report Description */}
      <div className="sr-section">
        <h2 className="sr-section-title">Report Description</h2>
        <div className="sr-button-group">
          <button className="sr-btn" onClick={handleAutoGenerate}>
            Auto-Generate Description
          </button>
          <div className="sr-phrases-container">
            <select
              className="sr-phrase-select"
              value={selectedPhrase}
              onChange={e => setSelectedPhrase(e.target.value)}
            >
              <option value="">-- Select Premade Phrase --</option>
              {Object.entries(phrases).map(([key, text]) => (
                <option key={key} value={text}>
                  {key}
                </option>
              ))}
            </select>
            <button className="sr-btn sr-btn-secondary" onClick={handleInsertPhrase}>
              Insert Phrase
            </button>
            <button className="sr-btn sr-btn-secondary" onClick={handleManagePhrases}>
              Manage Phrases
            </button>
          </div>
        </div>
        <textarea
          ref={textareaRef}
          className="sr-textarea"
          value={description}
          onChange={e => setDescription(e.target.value)}
          placeholder="Enter report description here..."
        />
        <div className="sr-button-group">
          <button className="sr-btn" onClick={handleSendReport}>
            Send Report to API
          </button>
          <button
            className="sr-btn"
            onClick={handleSavePdf}
            disabled={isSavingPdf}
          >
            {isSavingPdf ? 'Saving PDF...' : 'Save PDF to API'}
          </button>
        </div>
      </div>

      {/* Login Modal */}
      <LoginModal
        show={showLoginModal}
        onClose={() => {
          setShowLoginModal(false);
          setPendingAction(null);
        }}
        onLoginSuccess={handleLoginSuccess}
      />
    </div>
  );
};

export default SRReport;
