import { Measurement } from './constants';

const BIRADS_ORDER = ['0', '1', '2', '3', '4', '4a', '4b', '4c', '5', '6'];

export function extractHighestBiRads(measurements: Measurement[]): string {
  const biRadses = measurements.map(m => m.biRads).filter(c => c);
  if (biRadses.length === 0) {
    return '';
  }
  return biRadses.reduce((max, biRads) => {
    const maxIdx = BIRADS_ORDER.indexOf(String(max));
    const biRadsIdx = BIRADS_ORDER.indexOf(String(biRads));
    return biRadsIdx > maxIdx ? biRads : max;
  }, '0');
}

export function generateRecommendation(finalBirads: string): string {
  switch (finalBirads) {
    case '6':
      return 'Known biopsy-proven malignancy.';
    case '5':
    case '4c':
      return 'Biopsy recommended.';
    case '4b':
    case '4a':
    case '4':
      return 'Biopsy should be considered.';
    case '3':
      return 'Short-interval follow-up in 6 months.';
    case '2':
      return 'Benign finding. Routine follow-up.';
    case '1':
      return 'Negative. Continue routine screening.';
    case '0':
      return 'Additional imaging needed.';
    default:
      return '';
  }
}

function getBiRadsDescription(biRads: string): string {
  switch (biRads) {
    case '6':
      return `BI-RADS 6: Known biopsy-proven malignancy.`;
    case '5':
    case '4c':
      return `BI-RADS ${biRads}: Highly suggestive of malignancy. Biopsy recommended.`;
    case '4b':
    case '4a':
    case '4':
      return `BI-RADS ${biRads}: Suspicious abnormality. Biopsy should be considered.`;
    case '3':
      return `BI-RADS 3: Probably benign finding. Short-interval follow-up suggested.`;
    case '2':
      return `BI-RADS 2: Benign finding.`;
    case '1':
      return `BI-RADS 1: Negative.`;
    case '0':
      return `BI-RADS 0: Incomplete. Additional imaging needed.`;
    default:
      return 'No BI-RADS category assigned.';
  }
}

export function autoGenerateDescription(measurements: Measurement[]): string {
  let description = `FINDINGS:\n\n`;

  measurements.forEach((m, i) => {
    const latLabel = m.laterality ? ` (${m.laterality})` : '';
    description += `${i + 1}. Lesion ${i + 1}${latLabel}:\n`;
    if (m.frameRange) description += `   - Frame Range: ${m.frameRange}\n`;
    if (m.position) description += `   - Position: ${m.position}\n`;
    if (m.size) description += `   - Size: ${m.size} mm\n`;
    if (m.maxSurfVol) description += `   - Max/Surface/Volume: ${m.maxSurfVol}\n`;
    if (m.nature) description += `   - Nature: ${m.nature}\n`;
    if (m.maligPercent) description += `   - Malignancy %: ${m.maligPercent}\n`;
    if (m.echo && m.includeEcho !== false) description += `   - Echo Pattern: ${m.echo}\n`;
    if (m.shape && m.includeShape !== false) description += `   - Shape: ${m.shape}\n`;
    if (m.orientation && m.includeOrientation !== false)
      description += `   - Orientation: ${m.orientation}\n`;
    if (m.margin && m.includeMargin !== false) description += `   - Margin: ${m.margin}\n`;
    description += `\n`;
  });

  description += `\nCOMMENT:\n\n`;
  description += `\nBI-RADS CATEGORY:\n`;

  const highestBiRads = extractHighestBiRads(measurements);
  description += getBiRadsDescription(highestBiRads) + '\n';

  return description;
}

export function sortMeasurementsByFrame(measurements: Measurement[]): Measurement[] {
  const lateralityOrder = (lat: string): number => {
    const upper = (lat || '').toUpperCase();
    if (upper === 'R') return 0;
    if (upper === 'L') return 1;
    return 2; // empty or unknown → last
  };

  const extractFrameNums = (frameRange: string): [number, number] => {
    if (!frameRange) return [0, 0];
    const str = String(frameRange);
    const match = str.match(/(\d+)\D+(\d+)/);
    if (match) {
      return [parseInt(match[1], 10), parseInt(match[2], 10)];
    }
    const single = str.match(/(\d+)/);
    return single ? [parseInt(single[1], 10), 0] : [0, 0];
  };

  return [...measurements].sort((a, b) => {
    // Primary: Laterality (R → L → empty)
    const latDiff = lateralityOrder(a.laterality) - lateralityOrder(b.laterality);
    if (latDiff !== 0) return latDiff;

    // Secondary: Frame range
    const [a1, a2] = extractFrameNums(a.frameRange);
    const [b1, b2] = extractFrameNums(b.frameRange);
    return a1 !== b1 ? a1 - b1 : a2 - b2;
  });
}
